macos_instance:
  image: ghcr.io/cirruslabs/macos-monterey-xcode:latest

task:
  name: AppleM1/LLVM
  compile_script:
  - brew install llvm
  - export PATH=/opt/homebrew/opt/llvm/bin:$PATH
  - export LDFLAGS="-L/opt/homebrew/opt/llvm/lib"
  - export CPPFLAGS="-I/opt/homebrew/opt/llvm/include"
  - make TARGET=VORTEX USE_OPENMP=1 CC=clang

macos_instance:
  image: ghcr.io/cirruslabs/macos-monterey-xcode:13.4
task:
  name: AppleM1/LLVM x86_64 xbuild
  compile_script:
  - #brew install llvm
  - export #PATH=/opt/homebrew/opt/llvm/bin:$PATH
  - export #LDFLAGS="-L/opt/homebrew/opt/llvm/lib"
  - export #CPPFLAGS="-I/opt/homebrew/opt/llvm/include" 
  - export ARCHS="i386 x86_64"
  - export ARCHS_STANDARD="i386 x86_64"
  - export ARCHS_STANDARD_32_64_BIT="i386 x86_64"
  - export ARCHS_STANDARD_64_BIT=x86_64
  - export ARCHS_STANDARD_INCLUDING_64_BIT="i386 x86_64"
  - export ARCHS_UNIVERSAL_IPHONE_OS="i386 x86_64"
  - export VALID_ARCHS="i386 x86_64"
  - #find /Applications/Xcode-13.4.1.app -name libunwind.dylib
  - export CC=/Applications/Xcode-13.4.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
  - export CFLAGS="-O2 -unwindlib=none -Wno-macro-redefined -isysroot /Applications/Xcode-13.4.1.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator15.5.sdk -arch x86_64 -miphoneos-version-min=10.0"
  - make TARGET=CORE2 DYNAMIC_ARCH=1 NUM_THREADS=32 HOSTCC=clang NOFORTRAN=1
  always:
    config_artifacts:
      path: "*conf*"
      type: text/plain
#  lib_artifacts:
#    path: "libopenblas*"
#    type: application/octet-streamm


task:
  name: NeoverseN1
  arm_container:
    image: node:latest
  compile_script:
  - make
  
task:
  name: NeoverseN1-OMP
  arm_container:
    image: node:latest
    cpu: 8
  compile_script:
  - make USE_OPENMP=1
  
#task:
#  name: Windows/LLVM16     --- too slow ---
#  windows_container:
#    image: cirrusci/windowsservercore:cmake-2021.12.07
#  install_script: 
#    - choco list --localonly
#    - choco install -y llvm
#    - # choco install -y cmake --installargs '"ADD_CMAKE_TO_PATH=System"'
#    - choco install -y ninja
#    - refreshenv
#    - cd "c:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Auxiliary/Build"
#    - vcvarsall x64
#    - cd "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build"
#    - cmake -S . -B build -G "Ninja" -DCMAKE_CXX_COMPILER=clang-cl -DCMAKE_C_COMPILER=clang-cl -DCMAKE_MT=mt -DCMAKE_BUILD_TYPE=Release
#    - cd build
#    - cmake --build .
#    - ctest
